---
# group_vars/registry/main.yml

harbor_artifact_path:       harbor
harbor_install_parent:      "{{ install_root }}"
harbor_data_volume:         /data
harbor_http_port:           80
harbor_https_port:          443
harbor_with_trivy:          false

harbor_admin_password:      "{{ vault_harbor_admin_password }}"
harbor_db_password:         "{{ vault_harbor_db_password }}"

harbor_projects:
  - name: sup-services
    public: true
  - name: tanzu-packages
    public: true
  - name: tkg
    public: true

harbor_tls_mode:            ipa
harbor_tls_cert:            "/etc/pki/tls/certs/{{ harbor_hostname }}.crt"
harbor_tls_key:             "/etc/pki/tls/private/{{ harbor_hostname }}.key"

docker_offline_source:      yum
docker_offline_rpm_path:    "{{ harbor_artifact_path }}/docker"

firewall_open_tcp_ports:
  - 22
  - "{{ harbor_http_port }}"
  - "{{ harbor_https_port }}"
