---
# tasks file for configure_harbor_projects
#
# 4-state dispatcher: desired_state present | absent (started / stopped reserved)

- name: Converge to present
  ansible.builtin.include_tasks: is_present.yml
  when: desired_state | default('present') == 'present'

- name: Converge to absent
  ansible.builtin.include_tasks: is_absent.yml
  when: desired_state | default('present') == 'absent'

# - name: Converge to started
#   ansible.builtin.include_tasks: is_started.yml
#   when: desired_state | default('present') == 'started'

# - name: Converge to stopped
#   ansible.builtin.include_tasks: is_stopped.yml
#   when: desired_state | default('present') == 'stopped'
